# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'folding.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *

from . import icons_rc

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(640, 480)
        self.sequenceUrlEdit = QLineEdit(Dialog)
        self.sequenceUrlEdit.setObjectName(u"sequenceUrlEdit")
        self.sequenceUrlEdit.setGeometry(QRect(20, 20, 601, 30))
        self.horizontalLayoutWidget = QWidget(Dialog)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(230, 60, 191, 61))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.unpackButton = QPushButton(self.horizontalLayoutWidget)
        self.unpackButton.setObjectName(u"unpackButton")
        icon = QIcon()
        icon.addFile(u":/assets/down.png", QSize(), QIcon.Normal, QIcon.Off)
        self.unpackButton.setIcon(icon)
        self.unpackButton.setIconSize(QSize(36, 36))

        self.horizontalLayout.addWidget(self.unpackButton)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer)

        self.packButton = QPushButton(self.horizontalLayoutWidget)
        self.packButton.setObjectName(u"packButton")
        icon1 = QIcon()
        icon1.addFile(u":/assets/up.png", QSize(), QIcon.Normal, QIcon.Off)
        self.packButton.setIcon(icon1)
        self.packButton.setIconSize(QSize(36, 36))

        self.horizontalLayout.addWidget(self.packButton)

        self.urlListEdit = QPlainTextEdit(Dialog)
        self.urlListEdit.setObjectName(u"urlListEdit")
        self.urlListEdit.setGeometry(QRect(20, 135, 601, 281))
        self.sequenceUrlOpen = QPushButton(Dialog)
        self.sequenceUrlOpen.setObjectName(u"sequenceUrlOpen")
        self.sequenceUrlOpen.setGeometry(QRect(570, 70, 51, 30))
        self.sequenceUrlClear = QPushButton(Dialog)
        self.sequenceUrlClear.setObjectName(u"sequenceUrlClear")
        self.sequenceUrlClear.setGeometry(QRect(510, 70, 51, 30))
        icon2 = QIcon()
        icon2.addFile(u":/assets/clear.png", QSize(), QIcon.Normal, QIcon.Off)
        self.sequenceUrlClear.setIcon(icon2)
        self.label_2 = QLabel(Dialog)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(533, 50, 21, 18))
        font = QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.sequenceUrlClipboard = QPushButton(Dialog)
        self.sequenceUrlClipboard.setObjectName(u"sequenceUrlClipboard")
        self.sequenceUrlClipboard.setGeometry(QRect(20, 70, 51, 30))
        icon3 = QIcon()
        icon3.addFile(u":/assets/clipboard.png", QSize(), QIcon.Normal, QIcon.Off)
        self.sequenceUrlClipboard.setIcon(icon3)
        self.sequenceUrlClipboard.setIconSize(QSize(24, 24))
        self.urlListClear = QPushButton(Dialog)
        self.urlListClear.setObjectName(u"urlListClear")
        self.urlListClear.setGeometry(QRect(507, 438, 51, 30))
        self.urlListClear.setIcon(icon2)
        self.urlListClipboard = QPushButton(Dialog)
        self.urlListClipboard.setObjectName(u"urlListClipboard")
        self.urlListClipboard.setGeometry(QRect(17, 438, 51, 30))
        self.urlListClipboard.setIcon(icon3)
        self.urlListClipboard.setIconSize(QSize(24, 24))
        self.urlListOpen = QPushButton(Dialog)
        self.urlListOpen.setObjectName(u"urlListOpen")
        self.urlListOpen.setGeometry(QRect(567, 438, 51, 30))
        self.urlListPasteClipboard = QPushButton(Dialog)
        self.urlListPasteClipboard.setObjectName(u"urlListPasteClipboard")
        self.urlListPasteClipboard.setGeometry(QRect(80, 438, 41, 30))
        icon4 = QIcon()
        icon4.addFile(u":/assets/paste_from_clipboard.png", QSize(), QIcon.Normal, QIcon.Off)
        self.urlListPasteClipboard.setIcon(icon4)
        self.urlListPasteClipboard.setIconSize(QSize(36, 36))
        self.sequenceUrlPasteClipboard = QPushButton(Dialog)
        self.sequenceUrlPasteClipboard.setObjectName(u"sequenceUrlPasteClipboard")
        self.sequenceUrlPasteClipboard.setGeometry(QRect(80, 70, 41, 30))
        self.sequenceUrlPasteClipboard.setIcon(icon4)
        self.sequenceUrlPasteClipboard.setIconSize(QSize(36, 36))
        self.cancelButton = QPushButton(Dialog)
        self.cancelButton.setObjectName(u"cancelButton")
        self.cancelButton.setGeometry(QRect(270, 438, 107, 30))
        icon5 = QIcon()
        icon5.addFile(u":/assets/cancel.png", QSize(), QIcon.Normal, QIcon.Off)
        self.cancelButton.setIcon(icon5)
        self.cancelButton.setIconSize(QSize(24, 24))
        self.label_9 = QLabel(Dialog)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(40, 42, 21, 31))
        font1 = QFont()
        font1.setPointSize(14)
        font1.setBold(True)
        font1.setWeight(75)
        self.label_9.setFont(font1)
        self.label_10 = QLabel(Dialog)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(97, 42, 21, 31))
        self.label_10.setFont(font1)
        self.label_12 = QLabel(Dialog)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(592, 42, 21, 31))
        self.label_12.setFont(font1)
        self.label_11 = QLabel(Dialog)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(38, 409, 21, 31))
        self.label_11.setFont(font1)
        self.label_13 = QLabel(Dialog)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(97, 409, 21, 31))
        self.label_13.setFont(font1)
        self.label_3 = QLabel(Dialog)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(529, 417, 21, 18))
        self.label_3.setFont(font)
        self.label_14 = QLabel(Dialog)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(587, 409, 21, 31))
        self.label_14.setFont(font1)
        QWidget.setTabOrder(self.sequenceUrlEdit, self.unpackButton)
        QWidget.setTabOrder(self.unpackButton, self.packButton)
        QWidget.setTabOrder(self.packButton, self.sequenceUrlOpen)
        QWidget.setTabOrder(self.sequenceUrlOpen, self.urlListEdit)
        QWidget.setTabOrder(self.urlListEdit, self.urlListOpen)
        QWidget.setTabOrder(self.urlListOpen, self.sequenceUrlClipboard)
        QWidget.setTabOrder(self.sequenceUrlClipboard, self.sequenceUrlClear)
        QWidget.setTabOrder(self.sequenceUrlClear, self.urlListClipboard)
        QWidget.setTabOrder(self.urlListClipboard, self.urlListClear)

        self.retranslateUi(Dialog)
        self.cancelButton.clicked.connect(Dialog.close)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"URL folding / unfolding", None))
        self.sequenceUrlEdit.setPlaceholderText(QCoreApplication.translate("Dialog", u"sequence URL", None))
#if QT_CONFIG(tooltip)
        self.unpackButton.setToolTip(QCoreApplication.translate("Dialog", u"unfold (unpack)", None))
#endif // QT_CONFIG(tooltip)
        self.unpackButton.setText("")
#if QT_CONFIG(tooltip)
        self.packButton.setToolTip(QCoreApplication.translate("Dialog", u"fold (pack)", None))
#endif // QT_CONFIG(tooltip)
        self.packButton.setText("")
        self.urlListEdit.setPlaceholderText(QCoreApplication.translate("Dialog", u"list of URLs", None))
#if QT_CONFIG(tooltip)
        self.sequenceUrlOpen.setToolTip(QCoreApplication.translate("Dialog", u"open images in JiVE", None))
#endif // QT_CONFIG(tooltip)
        self.sequenceUrlOpen.setText(QCoreApplication.translate("Dialog", u"Open", None))
#if QT_CONFIG(tooltip)
        self.sequenceUrlClear.setToolTip(QCoreApplication.translate("Dialog", u"clear", None))
#endif // QT_CONFIG(tooltip)
        self.sequenceUrlClear.setText("")
        self.label_2.setText(QCoreApplication.translate("Dialog", u"|", None))
#if QT_CONFIG(tooltip)
        self.sequenceUrlClipboard.setToolTip(QCoreApplication.translate("Dialog", u"copy to clipboard", None))
#endif // QT_CONFIG(tooltip)
        self.sequenceUrlClipboard.setText("")
#if QT_CONFIG(tooltip)
        self.urlListClear.setToolTip(QCoreApplication.translate("Dialog", u"clear", None))
#endif // QT_CONFIG(tooltip)
        self.urlListClear.setText("")
#if QT_CONFIG(tooltip)
        self.urlListClipboard.setToolTip(QCoreApplication.translate("Dialog", u"copy to clipboard", None))
#endif // QT_CONFIG(tooltip)
        self.urlListClipboard.setText("")
#if QT_CONFIG(tooltip)
        self.urlListOpen.setToolTip(QCoreApplication.translate("Dialog", u"open images in JiVE", None))
#endif // QT_CONFIG(tooltip)
        self.urlListOpen.setText(QCoreApplication.translate("Dialog", u"Open", None))
#if QT_CONFIG(tooltip)
        self.urlListPasteClipboard.setToolTip(QCoreApplication.translate("Dialog", u"paste from clipboard", None))
#endif // QT_CONFIG(tooltip)
        self.urlListPasteClipboard.setText("")
#if QT_CONFIG(tooltip)
        self.sequenceUrlPasteClipboard.setToolTip(QCoreApplication.translate("Dialog", u"paste from clipboard", None))
#endif // QT_CONFIG(tooltip)
        self.sequenceUrlPasteClipboard.setText("")
        self.cancelButton.setText(QCoreApplication.translate("Dialog", u" &Cancel", None))
        self.label_9.setText(QCoreApplication.translate("Dialog", u"\u2193", None))
        self.label_10.setText(QCoreApplication.translate("Dialog", u"\u2191", None))
        self.label_12.setText(QCoreApplication.translate("Dialog", u"\u2193", None))
        self.label_11.setText(QCoreApplication.translate("Dialog", u"\u2193", None))
        self.label_13.setText(QCoreApplication.translate("Dialog", u"\u2191", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"|", None))
        self.label_14.setText(QCoreApplication.translate("Dialog", u"\u2193", None))
    # retranslateUi

