# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'tabs.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

from . import icons_rc

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(640, 480)
        Dialog.setModal(False)
        self.buttonBox = QDialogButtonBox(Dialog)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(370, 430, 251, 32))
        self.buttonBox.setOrientation(Qt.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.Cancel|QDialogButtonBox.Ok)
        self.tabs = QTabWidget(Dialog)
        self.tabs.setObjectName(u"tabs")
        self.tabs.setEnabled(True)
        self.tabs.setGeometry(QRect(20, 20, 601, 391))
        self.tab_0 = QWidget()
        self.tab_0.setObjectName(u"tab_0")
        self.frame = QFrame(self.tab_0)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 10, 581, 341))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.urlLineEdit = QLineEdit(self.frame)
        self.urlLineEdit.setObjectName(u"urlLineEdit")
        self.urlLineEdit.setGeometry(QRect(20, 20, 541, 30))
        self.extractButton = QPushButton(self.frame)
        self.extractButton.setObjectName(u"extractButton")
        self.extractButton.setGeometry(QRect(20, 179, 101, 41))
        icon = QIcon()
        icon.addFile(u":/assets/ok.png", QSize(), QIcon.Normal, QIcon.Off)
        self.extractButton.setIcon(icon)
        self.extractButton.setIconSize(QSize(28, 28))
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 70, 71, 18))
        self.distanceSpinBox = QSpinBox(self.frame)
        self.distanceSpinBox.setObjectName(u"distanceSpinBox")
        self.distanceSpinBox.setGeometry(QRect(104, 64, 52, 28))
        self.distanceSpinBox.setValue(10)
        self.getLinksCheckBox = QCheckBox(self.frame)
        self.getLinksCheckBox.setObjectName(u"getLinksCheckBox")
        self.getLinksCheckBox.setGeometry(QRect(20, 110, 141, 23))
        self.getLinksCheckBox.setChecked(True)
        self.getImagesCheckBox = QCheckBox(self.frame)
        self.getImagesCheckBox.setObjectName(u"getImagesCheckBox")
        self.getImagesCheckBox.setGeometry(QRect(20, 140, 141, 23))
        self.getImagesCheckBox.setChecked(True)
        self.clearButton = QPushButton(self.frame)
        self.clearButton.setObjectName(u"clearButton")
        self.clearButton.setGeometry(QRect(520, 60, 41, 30))
        icon1 = QIcon()
        icon1.addFile(u":/assets/clear.png", QSize(), QIcon.Normal, QIcon.Off)
        self.clearButton.setIcon(icon1)
        self.label_2 = QLabel(self.frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 237, 74, 18))
        self.miniLogTextEdit = QPlainTextEdit(self.frame)
        self.miniLogTextEdit.setObjectName(u"miniLogTextEdit")
        self.miniLogTextEdit.setGeometry(QRect(20, 260, 541, 71))
        self.miniLogTextEdit.setReadOnly(True)
        self.clearButton_2 = QPushButton(self.frame)
        self.clearButton_2.setObjectName(u"clearButton_2")
        self.clearButton_2.setGeometry(QRect(520, 220, 41, 30))
        self.clearButton_2.setIcon(icon1)
        self.label_3 = QLabel(self.frame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(497, 53, 21, 41))
        font = QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_4 = QLabel(self.frame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(497, 213, 21, 41))
        self.label_4.setFont(font)
        self.tabs.addTab(self.tab_0, "")
        self.tab_1 = QWidget()
        self.tab_1.setObjectName(u"tab_1")
        self.verticalLayoutWidget = QWidget(self.tab_1)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(10, 40, 581, 281))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.tab1TextEdit = QPlainTextEdit(self.verticalLayoutWidget)
        self.tab1TextEdit.setObjectName(u"tab1TextEdit")
        self.tab1TextEdit.setReadOnly(False)

        self.verticalLayout.addWidget(self.tab1TextEdit)

        self.tab1Label = QLabel(self.tab_1)
        self.tab1Label.setObjectName(u"tab1Label")
        self.tab1Label.setGeometry(QRect(10, 10, 321, 18))
        self.label_5 = QLabel(self.tab_1)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(11, 330, 301, 18))
        self.tab1CountLabel = QLabel(self.tab_1)
        self.tab1CountLabel.setObjectName(u"tab1CountLabel")
        self.tab1CountLabel.setGeometry(QRect(510, 10, 74, 18))
        self.tab1CopyButton = QPushButton(self.tab_1)
        self.tab1CopyButton.setObjectName(u"tab1CopyButton")
        self.tab1CopyButton.setGeometry(QRect(550, 325, 41, 30))
        icon2 = QIcon()
        icon2.addFile(u":/assets/clipboard.png", QSize(), QIcon.Normal, QIcon.Off)
        self.tab1CopyButton.setIcon(icon2)
        self.tab1CopyButton.setIconSize(QSize(26, 26))
        self.label_9 = QLabel(self.tab_1)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(520, 330, 21, 18))
        font1 = QFont()
        font1.setPointSize(14)
        font1.setBold(True)
        font1.setWeight(75)
        self.label_9.setFont(font1)
        self.tabs.addTab(self.tab_1, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.verticalLayoutWidget_2 = QWidget(self.tab_2)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(10, 40, 581, 281))
        self.verticalLayout_2 = QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.tab2TextEdit = QPlainTextEdit(self.verticalLayoutWidget_2)
        self.tab2TextEdit.setObjectName(u"tab2TextEdit")
        self.tab2TextEdit.setReadOnly(False)

        self.verticalLayout_2.addWidget(self.tab2TextEdit)

        self.tab2Label = QLabel(self.tab_2)
        self.tab2Label.setObjectName(u"tab2Label")
        self.tab2Label.setGeometry(QRect(10, 10, 331, 18))
        self.label_6 = QLabel(self.tab_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(11, 330, 301, 18))
        self.tab2CountLabel = QLabel(self.tab_2)
        self.tab2CountLabel.setObjectName(u"tab2CountLabel")
        self.tab2CountLabel.setGeometry(QRect(510, 10, 74, 18))
        self.tab2CopyButton = QPushButton(self.tab_2)
        self.tab2CopyButton.setObjectName(u"tab2CopyButton")
        self.tab2CopyButton.setGeometry(QRect(550, 325, 41, 30))
        self.tab2CopyButton.setIcon(icon2)
        self.tab2CopyButton.setIconSize(QSize(26, 26))
        self.label_10 = QLabel(self.tab_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(520, 330, 21, 18))
        self.label_10.setFont(font1)
        self.tabs.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.verticalLayoutWidget_3 = QWidget(self.tab_3)
        self.verticalLayoutWidget_3.setObjectName(u"verticalLayoutWidget_3")
        self.verticalLayoutWidget_3.setGeometry(QRect(10, 40, 581, 281))
        self.verticalLayout_3 = QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.tab3TextEdit = QPlainTextEdit(self.verticalLayoutWidget_3)
        self.tab3TextEdit.setObjectName(u"tab3TextEdit")
        self.tab3TextEdit.setReadOnly(False)

        self.verticalLayout_3.addWidget(self.tab3TextEdit)

        self.tab3Label = QLabel(self.tab_3)
        self.tab3Label.setObjectName(u"tab3Label")
        self.tab3Label.setGeometry(QRect(10, 10, 311, 18))
        self.label_7 = QLabel(self.tab_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(11, 330, 311, 18))
        self.tab3CountLabel = QLabel(self.tab_3)
        self.tab3CountLabel.setObjectName(u"tab3CountLabel")
        self.tab3CountLabel.setGeometry(QRect(510, 10, 74, 18))
        self.tab3CopyButton = QPushButton(self.tab_3)
        self.tab3CopyButton.setObjectName(u"tab3CopyButton")
        self.tab3CopyButton.setGeometry(QRect(550, 325, 41, 30))
        self.tab3CopyButton.setIcon(icon2)
        self.tab3CopyButton.setIconSize(QSize(26, 26))
        self.label_11 = QLabel(self.tab_3)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(520, 330, 21, 18))
        self.label_11.setFont(font1)
        self.tabs.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.verticalLayoutWidget_4 = QWidget(self.tab_4)
        self.verticalLayoutWidget_4.setObjectName(u"verticalLayoutWidget_4")
        self.verticalLayoutWidget_4.setGeometry(QRect(10, 40, 581, 281))
        self.verticalLayout_4 = QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.tab4TextEdit = QPlainTextEdit(self.verticalLayoutWidget_4)
        self.tab4TextEdit.setObjectName(u"tab4TextEdit")
        self.tab4TextEdit.setReadOnly(False)

        self.verticalLayout_4.addWidget(self.tab4TextEdit)

        self.tab4Label = QLabel(self.tab_4)
        self.tab4Label.setObjectName(u"tab4Label")
        self.tab4Label.setGeometry(QRect(10, 10, 331, 18))
        self.label_8 = QLabel(self.tab_4)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(11, 330, 291, 18))
        self.tab4CountLabel = QLabel(self.tab_4)
        self.tab4CountLabel.setObjectName(u"tab4CountLabel")
        self.tab4CountLabel.setGeometry(QRect(510, 10, 74, 18))
        self.tab4CopyButton = QPushButton(self.tab_4)
        self.tab4CopyButton.setObjectName(u"tab4CopyButton")
        self.tab4CopyButton.setGeometry(QRect(550, 325, 41, 30))
        self.tab4CopyButton.setIcon(icon2)
        self.tab4CopyButton.setIconSize(QSize(26, 26))
        self.label_12 = QLabel(self.tab_4)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(520, 330, 21, 18))
        self.label_12.setFont(font1)
        self.tabs.addTab(self.tab_4, "")
        QWidget.setTabOrder(self.urlLineEdit, self.distanceSpinBox)
        QWidget.setTabOrder(self.distanceSpinBox, self.getLinksCheckBox)
        QWidget.setTabOrder(self.getLinksCheckBox, self.getImagesCheckBox)
        QWidget.setTabOrder(self.getImagesCheckBox, self.extractButton)
        QWidget.setTabOrder(self.extractButton, self.clearButton)
        QWidget.setTabOrder(self.clearButton, self.tabs)
        QWidget.setTabOrder(self.tabs, self.tab2TextEdit)
        QWidget.setTabOrder(self.tab2TextEdit, self.tab3TextEdit)
        QWidget.setTabOrder(self.tab3TextEdit, self.tab4TextEdit)
        QWidget.setTabOrder(self.tab4TextEdit, self.tab1TextEdit)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.clearButton_2.clicked.connect(self.miniLogTextEdit.clear)

        self.tabs.setCurrentIndex(4)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Extract images from a webpage", None))
        self.urlLineEdit.setPlaceholderText(QCoreApplication.translate("Dialog", u"URL of the webpage", None))
        self.extractButton.setText(QCoreApplication.translate("Dialog", u"  E&xtract", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"Distance:", None))
        self.getLinksCheckBox.setText(QCoreApplication.translate("Dialog", u"get links", None))
        self.getImagesCheckBox.setText(QCoreApplication.translate("Dialog", u"get images", None))
#if QT_CONFIG(tooltip)
        self.clearButton.setToolTip(QCoreApplication.translate("Dialog", u"clear", None))
#endif // QT_CONFIG(tooltip)
        self.clearButton.setText("")
        self.label_2.setText(QCoreApplication.translate("Dialog", u"Mini log:", None))
#if QT_CONFIG(tooltip)
        self.clearButton_2.setToolTip(QCoreApplication.translate("Dialog", u"clear", None))
#endif // QT_CONFIG(tooltip)
        self.clearButton_2.setText("")
        self.label_3.setText(QCoreApplication.translate("Dialog", u"\u2514", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"\u250c", None))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_0), QCoreApplication.translate("Dialog", u"Tab 0", None))
        self.tab1TextEdit.setPlaceholderText(QCoreApplication.translate("Dialog", u"empty", None))
        self.tab1Label.setText(QCoreApplication.translate("Dialog", u"Elements were found in this order:", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"Press OK to open these images", None))
        self.tab1CountLabel.setText(QCoreApplication.translate("Dialog", u"Count: 0", None))
#if QT_CONFIG(tooltip)
        self.tab1CopyButton.setToolTip(QCoreApplication.translate("Dialog", u"copy to clipboard", None))
#endif // QT_CONFIG(tooltip)
        self.tab1CopyButton.setText("")
        self.label_9.setText(QCoreApplication.translate("Dialog", u"\u2192", None))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_1), QCoreApplication.translate("Dialog", u"Tab 1", None))
        self.tab2TextEdit.setPlaceholderText(QCoreApplication.translate("Dialog", u"empty", None))
        self.tab2Label.setText(QCoreApplication.translate("Dialog", u"Sorting: OFF; this is the largest cluster:", None))
        self.label_6.setText(QCoreApplication.translate("Dialog", u"Press OK to open these images", None))
        self.tab2CountLabel.setText(QCoreApplication.translate("Dialog", u"Count: 0", None))
#if QT_CONFIG(tooltip)
        self.tab2CopyButton.setToolTip(QCoreApplication.translate("Dialog", u"copy to clipboard", None))
#endif // QT_CONFIG(tooltip)
        self.tab2CopyButton.setText("")
        self.label_10.setText(QCoreApplication.translate("Dialog", u"\u2192", None))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_2), QCoreApplication.translate("Dialog", u"Tab 2", None))
        self.tab3TextEdit.setPlaceholderText(QCoreApplication.translate("Dialog", u"empty", None))
        self.tab3Label.setText(QCoreApplication.translate("Dialog", u"Sorting: ON; no clustering:", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"Press OK to open these images", None))
        self.tab3CountLabel.setText(QCoreApplication.translate("Dialog", u"Count: 0", None))
#if QT_CONFIG(tooltip)
        self.tab3CopyButton.setToolTip(QCoreApplication.translate("Dialog", u"copy to clipboard", None))
#endif // QT_CONFIG(tooltip)
        self.tab3CopyButton.setText("")
        self.label_11.setText(QCoreApplication.translate("Dialog", u"\u2192", None))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_3), QCoreApplication.translate("Dialog", u"Tab 3", None))
        self.tab4TextEdit.setPlaceholderText(QCoreApplication.translate("Dialog", u"empty", None))
        self.tab4Label.setText(QCoreApplication.translate("Dialog", u"Sorting: ON; this is the largest cluster:", None))
        self.label_8.setText(QCoreApplication.translate("Dialog", u"Press OK to open these images", None))
        self.tab4CountLabel.setText(QCoreApplication.translate("Dialog", u"Count: 0", None))
#if QT_CONFIG(tooltip)
        self.tab4CopyButton.setToolTip(QCoreApplication.translate("Dialog", u"copy to clipboard", None))
#endif // QT_CONFIG(tooltip)
        self.tab4CopyButton.setText("")
        self.label_12.setText(QCoreApplication.translate("Dialog", u"\u2192", None))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_4), QCoreApplication.translate("Dialog", u"Tab 4", None))
    # retranslateUi

